import { ComponentDefinition, UIComponentType } from '@/types';

export const COMPONENT_DEFINITIONS: ComponentDefinition[] = [
  {
    type: 'View',
    label: 'Container',
    icon: 'crop-square',
    iconFamily: 'MaterialIcons',
    previewColor: '#6366F1',
    defaultProps: {
      backgroundColor: 'transparent',
      padding: 16,
      borderRadius: 0,
      flexDirection: 'column',
      alignItems: 'flex-start',
      minHeight: 60,
      borderWidth: 1,
      borderColor: '#E2E2EC',
    },
    propertyControls: [
      { kind: 'color', label: 'Background', key: 'backgroundColor' },
      { kind: 'number', label: 'Padding', key: 'padding', min: 0, max: 64, step: 2 },
      { kind: 'number', label: 'Border Radius', key: 'borderRadius', min: 0, max: 48, step: 2 },
      { kind: 'number', label: 'Min Height', key: 'minHeight', min: 20, max: 400, step: 4 },
      { kind: 'select', label: 'Direction', key: 'flexDirection', options: [
        { label: 'Column', value: 'column' },
        { label: 'Row', value: 'row' },
      ]},
      { kind: 'select', label: 'Align Items', key: 'alignItems', options: [
        { label: 'Start', value: 'flex-start' },
        { label: 'Center', value: 'center' },
        { label: 'End', value: 'flex-end' },
      ]},
      { kind: 'number', label: 'Border Width', key: 'borderWidth', min: 0, max: 4, step: 1 },
      { kind: 'color', label: 'Border Color', key: 'borderColor' },
    ],
  },
  {
    type: 'Text',
    label: 'Text',
    icon: 'text-fields',
    iconFamily: 'MaterialIcons',
    previewColor: '#8B5CF6',
    defaultProps: {
      content: 'Hello World',
      fontSize: 16,
      color: '#111128',
      fontWeight: '400',
      textAlign: 'left',
      lineHeight: 24,
    },
    propertyControls: [
      { kind: 'text', label: 'Content', key: 'content' },
      { kind: 'number', label: 'Font Size', key: 'fontSize', min: 8, max: 64, step: 1 },
      { kind: 'color', label: 'Color', key: 'color' },
      { kind: 'select', label: 'Font Weight', key: 'fontWeight', options: [
        { label: 'Regular', value: '400' },
        { label: 'Medium', value: '500' },
        { label: 'SemiBold', value: '600' },
        { label: 'Bold', value: '700' },
      ]},
      { kind: 'select', label: 'Align', key: 'textAlign', options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ]},
    ],
  },
  {
    type: 'Button',
    label: 'Button',
    icon: 'smart-button',
    iconFamily: 'MaterialIcons',
    previewColor: '#7C3AED',
    defaultProps: {
      label: 'Tap Me',
      backgroundColor: '#7C3AED',
      textColor: '#FFFFFF',
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 24,
      fontSize: 16,
      fontWeight: '600',
      fullWidth: false,
    },
    propertyControls: [
      { kind: 'text', label: 'Label', key: 'label' },
      { kind: 'color', label: 'Background', key: 'backgroundColor' },
      { kind: 'color', label: 'Text Color', key: 'textColor' },
      { kind: 'number', label: 'Border Radius', key: 'borderRadius', min: 0, max: 48, step: 2 },
      { kind: 'number', label: 'Font Size', key: 'fontSize', min: 10, max: 24, step: 1 },
      { kind: 'select', label: 'Font Weight', key: 'fontWeight', options: [
        { label: 'Regular', value: '400' },
        { label: 'Medium', value: '500' },
        { label: 'SemiBold', value: '600' },
        { label: 'Bold', value: '700' },
      ]},
      { kind: 'toggle', label: 'Full Width', key: 'fullWidth' },
    ],
  },
  {
    type: 'TextInput',
    label: 'Input',
    icon: 'input',
    iconFamily: 'MaterialIcons',
    previewColor: '#06B6D4',
    defaultProps: {
      placeholder: 'Type here...',
      borderColor: '#E2E2EC',
      borderRadius: 10,
      borderWidth: 1.5,
      backgroundColor: '#FFFFFF',
      padding: 14,
      fontSize: 16,
      color: '#111128',
    },
    propertyControls: [
      { kind: 'text', label: 'Placeholder', key: 'placeholder' },
      { kind: 'color', label: 'Background', key: 'backgroundColor' },
      { kind: 'color', label: 'Border Color', key: 'borderColor' },
      { kind: 'color', label: 'Text Color', key: 'color' },
      { kind: 'number', label: 'Border Radius', key: 'borderRadius', min: 0, max: 32, step: 2 },
      { kind: 'number', label: 'Font Size', key: 'fontSize', min: 10, max: 24, step: 1 },
      { kind: 'number', label: 'Padding', key: 'padding', min: 4, max: 32, step: 2 },
    ],
  },
  {
    type: 'Image',
    label: 'Image',
    icon: 'image',
    iconFamily: 'MaterialIcons',
    previewColor: '#F59E0B',
    defaultProps: {
      uri: 'https://picsum.photos/400/200',
      height: 200,
      borderRadius: 12,
      resizeMode: 'cover',
    },
    propertyControls: [
      { kind: 'text', label: 'Image URL', key: 'uri' },
      { kind: 'number', label: 'Height', key: 'height', min: 40, max: 400, step: 8 },
      { kind: 'number', label: 'Border Radius', key: 'borderRadius', min: 0, max: 48, step: 4 },
      { kind: 'select', label: 'Resize Mode', key: 'resizeMode', options: [
        { label: 'Cover', value: 'cover' },
        { label: 'Contain', value: 'contain' },
        { label: 'Stretch', value: 'stretch' },
      ]},
    ],
  },
  {
    type: 'Card',
    label: 'Card',
    icon: 'credit-card',
    iconFamily: 'Feather',
    previewColor: '#10B981',
    defaultProps: {
      title: 'Card Title',
      subtitle: 'Subtitle text goes here',
      backgroundColor: '#FFFFFF',
      padding: 20,
      borderRadius: 16,
      titleColor: '#111128',
      subtitleColor: '#5B5B7A',
      titleSize: 18,
      subtitleSize: 14,
    },
    propertyControls: [
      { kind: 'text', label: 'Title', key: 'title' },
      { kind: 'text', label: 'Subtitle', key: 'subtitle' },
      { kind: 'color', label: 'Background', key: 'backgroundColor' },
      { kind: 'color', label: 'Title Color', key: 'titleColor' },
      { kind: 'color', label: 'Subtitle Color', key: 'subtitleColor' },
      { kind: 'number', label: 'Padding', key: 'padding', min: 8, max: 48, step: 4 },
      { kind: 'number', label: 'Border Radius', key: 'borderRadius', min: 0, max: 32, step: 4 },
    ],
  },
  {
    type: 'Header',
    label: 'Header',
    icon: 'view-agenda',
    iconFamily: 'MaterialIcons',
    previewColor: '#EF4444',
    defaultProps: {
      title: 'App Header',
      backgroundColor: '#7C3AED',
      textColor: '#FFFFFF',
      fontSize: 20,
      paddingVertical: 18,
      paddingHorizontal: 20,
      showBack: false,
    },
    propertyControls: [
      { kind: 'text', label: 'Title', key: 'title' },
      { kind: 'color', label: 'Background', key: 'backgroundColor' },
      { kind: 'color', label: 'Text Color', key: 'textColor' },
      { kind: 'number', label: 'Font Size', key: 'fontSize', min: 14, max: 28, step: 1 },
      { kind: 'number', label: 'Vertical Padding', key: 'paddingVertical', min: 8, max: 40, step: 2 },
      { kind: 'toggle', label: 'Show Back Arrow', key: 'showBack' },
    ],
  },
  {
    type: 'Footer',
    label: 'Footer',
    icon: 'horizontal-rule',
    iconFamily: 'MaterialIcons',
    previewColor: '#6366F1',
    defaultProps: {
      text: '© 2026 My App',
      backgroundColor: '#F4F4F8',
      textColor: '#9494B0',
      fontSize: 13,
      paddingVertical: 16,
    },
    propertyControls: [
      { kind: 'text', label: 'Text', key: 'text' },
      { kind: 'color', label: 'Background', key: 'backgroundColor' },
      { kind: 'color', label: 'Text Color', key: 'textColor' },
      { kind: 'number', label: 'Font Size', key: 'fontSize', min: 10, max: 20, step: 1 },
      { kind: 'number', label: 'Vertical Padding', key: 'paddingVertical', min: 8, max: 40, step: 2 },
    ],
  },
  {
    type: 'Spacer',
    label: 'Spacer',
    icon: 'space-bar',
    iconFamily: 'MaterialIcons',
    previewColor: '#9CA3AF',
    defaultProps: {
      height: 24,
    },
    propertyControls: [
      { kind: 'number', label: 'Height', key: 'height', min: 4, max: 200, step: 4 },
    ],
  },
  {
    type: 'Divider',
    label: 'Divider',
    icon: 'minus',
    iconFamily: 'Feather',
    previewColor: '#D1D5DB',
    defaultProps: {
      color: '#E2E2EC',
      thickness: 1,
      marginVertical: 8,
    },
    propertyControls: [
      { kind: 'color', label: 'Color', key: 'color' },
      { kind: 'number', label: 'Thickness', key: 'thickness', min: 1, max: 8, step: 1 },
      { kind: 'number', label: 'Vertical Margin', key: 'marginVertical', min: 0, max: 32, step: 2 },
    ],
  },
  {
    type: 'ScrollView',
    label: 'Scroll',
    icon: 'swap-vert',
    iconFamily: 'MaterialIcons',
    previewColor: '#A78BFA',
    defaultProps: {
      backgroundColor: 'transparent',
      padding: 16,
      minHeight: 120,
      label: 'Scroll Area',
    },
    propertyControls: [
      { kind: 'text', label: 'Label', key: 'label' },
      { kind: 'color', label: 'Background', key: 'backgroundColor' },
      { kind: 'number', label: 'Padding', key: 'padding', min: 0, max: 48, step: 4 },
      { kind: 'number', label: 'Min Height', key: 'minHeight', min: 60, max: 400, step: 8 },
    ],
  },
  {
    type: 'FlatList',
    label: 'List',
    icon: 'format-list-bulleted',
    iconFamily: 'MaterialIcons',
    previewColor: '#34D399',
    defaultProps: {
      itemText: 'List item',
      itemCount: 3,
      itemBackgroundColor: '#FFFFFF',
      itemBorderRadius: 10,
      itemPadding: 14,
      itemFontSize: 15,
      itemColor: '#111128',
      gap: 10,
    },
    propertyControls: [
      { kind: 'text', label: 'Item Text', key: 'itemText' },
      { kind: 'number', label: 'Item Count', key: 'itemCount', min: 1, max: 10, step: 1 },
      { kind: 'color', label: 'Item Background', key: 'itemBackgroundColor' },
      { kind: 'color', label: 'Item Text Color', key: 'itemColor' },
      { kind: 'number', label: 'Item Padding', key: 'itemPadding', min: 6, max: 32, step: 2 },
      { kind: 'number', label: 'Item Font Size', key: 'itemFontSize', min: 10, max: 24, step: 1 },
      { kind: 'number', label: 'Border Radius', key: 'itemBorderRadius', min: 0, max: 24, step: 2 },
      { kind: 'number', label: 'Gap', key: 'gap', min: 0, max: 24, step: 2 },
    ],
  },
];

export const COMPONENT_MAP = COMPONENT_DEFINITIONS.reduce<Record<UIComponentType, ComponentDefinition>>(
  (acc, def) => {
    acc[def.type] = def;
    return acc;
  },
  {} as Record<UIComponentType, ComponentDefinition>
);

export function getDefaultProps(type: UIComponentType): Record<string, any> {
  return { ...(COMPONENT_MAP[type]?.defaultProps ?? {}) };
}
