import { Project, AppScreen, UIComponent, DEFAULT_THEME } from '@/types';

function id(): string {
  return Date.now().toString(36) + Math.random().toString(36).substring(2, 7);
}

function comp(type: UIComponent['type'], props: Record<string, any>): UIComponent {
  return { id: id(), type, props };
}

function screen(name: string, bg: string, components: UIComponent[]): AppScreen {
  return { id: id(), name, backgroundColor: bg, components };
}

export interface ProjectTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  category: string;
  project: Omit<Project, 'id' | 'createdAt' | 'updatedAt'>;
}

export const TEMPLATES: ProjectTemplate[] = [
  {
    id: 'todo',
    name: 'Todo List',
    description: 'A clean task management app with add/complete functionality',
    icon: 'check-circle',
    color: '#7C3AED',
    category: 'Productivity',
    project: {
      name: 'Todo App',
      theme: {
        ...DEFAULT_THEME,
        primaryColor: '#7C3AED',
        secondaryColor: '#A78BFA',
        backgroundColor: '#F4F4F8',
        surfaceColor: '#FFFFFF',
        textColor: '#111128',
        borderRadius: 12,
      },
      screens: [
        screen('Home', '#F4F4F8', [
          comp('Header', {
            title: 'My Tasks',
            backgroundColor: '#7C3AED',
            textColor: '#FFFFFF',
            fontSize: 22,
            paddingVertical: 20,
            showBack: false,
          }),
          comp('Spacer', { height: 16 }),
          comp('Card', {
            title: '📋 Today',
            subtitle: '3 tasks remaining',
            backgroundColor: '#FFFFFF',
            padding: 18,
            borderRadius: 14,
            titleColor: '#111128',
            subtitleColor: '#7C3AED',
            titleSize: 17,
            subtitleSize: 13,
          }),
          comp('Spacer', { height: 12 }),
          comp('FlatList', {
            itemText: '✓ Buy groceries',
            itemCount: 4,
            itemBackgroundColor: '#FFFFFF',
            itemBorderRadius: 12,
            itemPadding: 16,
            itemFontSize: 15,
            itemColor: '#111128',
            gap: 10,
          }),
          comp('Spacer', { height: 20 }),
          comp('Button', {
            label: '+ Add New Task',
            backgroundColor: '#7C3AED',
            textColor: '#FFFFFF',
            borderRadius: 14,
            paddingVertical: 16,
            fontSize: 16,
            fontWeight: '700',
            fullWidth: true,
            actionType: 'navigate',
            actionTarget: 'Add Task',
          }),
        ]),
        screen('Add Task', '#FFFFFF', [
          comp('Header', {
            title: 'New Task',
            backgroundColor: '#7C3AED',
            textColor: '#FFFFFF',
            fontSize: 20,
            paddingVertical: 18,
            showBack: true,
          }),
          comp('Spacer', { height: 24 }),
          comp('FormField', {
            label: 'Task Name',
            placeholder: 'What needs to be done?',
            labelColor: '#5B5B7A',
            inputBg: '#F4F4F8',
            borderRadius: 12,
          }),
          comp('Spacer', { height: 16 }),
          comp('FormField', {
            label: 'Due Date',
            placeholder: 'When is it due?',
            labelColor: '#5B5B7A',
            inputBg: '#F4F4F8',
            borderRadius: 12,
          }),
          comp('Spacer', { height: 24 }),
          comp('Button', {
            label: 'Save Task',
            backgroundColor: '#7C3AED',
            textColor: '#FFFFFF',
            borderRadius: 14,
            paddingVertical: 16,
            fontSize: 16,
            fontWeight: '700',
            fullWidth: true,
            actionType: 'alert',
            actionTarget: 'Task saved successfully!',
          }),
        ]),
      ],
    },
  },
  {
    id: 'notes',
    name: 'Notes App',
    description: 'Minimal note-taking with rich text and categories',
    icon: 'note-alt',
    color: '#F59E0B',
    category: 'Productivity',
    project: {
      name: 'Notes App',
      theme: {
        ...DEFAULT_THEME,
        primaryColor: '#F59E0B',
        secondaryColor: '#FCD34D',
        backgroundColor: '#FFFBEB',
        surfaceColor: '#FFFFFF',
        textColor: '#1C1917',
        borderRadius: 16,
      },
      screens: [
        screen('Notes', '#FFFBEB', [
          comp('Header', {
            title: 'My Notes',
            backgroundColor: '#F59E0B',
            textColor: '#FFFFFF',
            fontSize: 22,
            paddingVertical: 20,
            showBack: false,
          }),
          comp('Spacer', { height: 16 }),
          comp('Card', {
            title: 'Shopping List',
            subtitle: 'Milk, eggs, bread, butter...',
            backgroundColor: '#FFFBEB',
            padding: 18,
            borderRadius: 16,
            titleColor: '#1C1917',
            subtitleColor: '#78716C',
            titleSize: 16,
            subtitleSize: 13,
          }),
          comp('Spacer', { height: 8 }),
          comp('Card', {
            title: 'Meeting Notes',
            subtitle: 'Discuss Q2 roadmap, review metrics...',
            backgroundColor: '#FEF3C7',
            padding: 18,
            borderRadius: 16,
            titleColor: '#1C1917',
            subtitleColor: '#78716C',
            titleSize: 16,
            subtitleSize: 13,
          }),
          comp('Spacer', { height: 8 }),
          comp('Card', {
            title: 'Ideas',
            subtitle: 'New app feature — user profiles...',
            backgroundColor: '#ECFDF5',
            padding: 18,
            borderRadius: 16,
            titleColor: '#1C1917',
            subtitleColor: '#78716C',
            titleSize: 16,
            subtitleSize: 13,
          }),
          comp('Spacer', { height: 20 }),
          comp('Button', {
            label: '+ New Note',
            backgroundColor: '#F59E0B',
            textColor: '#FFFFFF',
            borderRadius: 16,
            paddingVertical: 16,
            fontSize: 16,
            fontWeight: '700',
            fullWidth: true,
            actionType: 'navigate',
            actionTarget: 'Write Note',
          }),
        ]),
        screen('Write Note', '#FFFFFF', [
          comp('Header', {
            title: 'New Note',
            backgroundColor: '#F59E0B',
            textColor: '#FFFFFF',
            fontSize: 20,
            paddingVertical: 18,
            showBack: true,
          }),
          comp('Spacer', { height: 16 }),
          comp('FormField', {
            label: 'Title',
            placeholder: 'Note title...',
            labelColor: '#78716C',
            inputBg: '#FFFBEB',
            borderRadius: 12,
          }),
          comp('Spacer', { height: 12 }),
          comp('View', {
            backgroundColor: '#FFFBEB',
            padding: 16,
            borderRadius: 12,
            borderWidth: 1,
            borderColor: '#FCD34D',
            minHeight: 200,
          }),
          comp('Spacer', { height: 20 }),
          comp('Button', {
            label: 'Save Note',
            backgroundColor: '#F59E0B',
            textColor: '#FFFFFF',
            borderRadius: 14,
            paddingVertical: 16,
            fontSize: 16,
            fontWeight: '700',
            fullWidth: true,
            actionType: 'alert',
            actionTarget: 'Note saved!',
          }),
        ]),
      ],
    },
  },
  {
    id: 'cardapio',
    name: 'Cardápio',
    description: 'App de restaurante com categorias e carrinho de compras',
    icon: 'restaurant',
    color: '#EF4444',
    category: 'Food & Drink',
    project: {
      name: 'Cardápio App',
      theme: {
        ...DEFAULT_THEME,
        primaryColor: '#EF4444',
        secondaryColor: '#F97316',
        backgroundColor: '#FFF5F5',
        surfaceColor: '#FFFFFF',
        textColor: '#1A0000',
        borderRadius: 14,
      },
      screens: [
        screen('Menu', '#FFF5F5', [
          comp('Header', {
            title: 'Restaurante Gourmet',
            backgroundColor: '#EF4444',
            textColor: '#FFFFFF',
            fontSize: 20,
            paddingVertical: 18,
            showBack: false,
          }),
          comp('Tabs', {
            tabs: ['Entradas', 'Principais', 'Sobremesas'],
            activeTab: 0,
            activeColor: '#EF4444',
            inactiveColor: '#9CA3AF',
            backgroundColor: '#FFFFFF',
          }),
          comp('Spacer', { height: 12 }),
          comp('Card', {
            title: 'Bruschetta Italiana',
            subtitle: 'Pão artesanal, tomate, manjericão • R$ 28',
            backgroundColor: '#FFFFFF',
            padding: 16,
            borderRadius: 14,
            titleColor: '#1A0000',
            subtitleColor: '#6B7280',
            titleSize: 16,
            subtitleSize: 13,
          }),
          comp('Spacer', { height: 8 }),
          comp('Card', {
            title: 'Carpaccio de Carne',
            subtitle: 'Molho especial, alcaparras, rúcula • R$ 42',
            backgroundColor: '#FFFFFF',
            padding: 16,
            borderRadius: 14,
            titleColor: '#1A0000',
            subtitleColor: '#6B7280',
            titleSize: 16,
            subtitleSize: 13,
          }),
          comp('Spacer', { height: 8 }),
          comp('Card', {
            title: 'Camarão ao Alho',
            subtitle: 'Camarão fresco, manteiga, alho • R$ 65',
            backgroundColor: '#FFFFFF',
            padding: 16,
            borderRadius: 14,
            titleColor: '#1A0000',
            subtitleColor: '#6B7280',
            titleSize: 16,
            subtitleSize: 13,
          }),
          comp('Spacer', { height: 16 }),
          comp('Button', {
            label: 'Ver Carrinho (3 itens)',
            backgroundColor: '#EF4444',
            textColor: '#FFFFFF',
            borderRadius: 14,
            paddingVertical: 16,
            fontSize: 16,
            fontWeight: '700',
            fullWidth: true,
            actionType: 'navigate',
            actionTarget: 'Carrinho',
          }),
        ]),
        screen('Carrinho', '#FFF5F5', [
          comp('Header', {
            title: 'Seu Pedido',
            backgroundColor: '#EF4444',
            textColor: '#FFFFFF',
            fontSize: 20,
            paddingVertical: 18,
            showBack: true,
          }),
          comp('Spacer', { height: 16 }),
          comp('FlatList', {
            itemText: 'Bruschetta Italiana',
            itemCount: 3,
            itemBackgroundColor: '#FFFFFF',
            itemBorderRadius: 12,
            itemPadding: 16,
            itemFontSize: 15,
            itemColor: '#1A0000',
            gap: 8,
          }),
          comp('Divider', { color: '#FECACA', marginVertical: 16, thickness: 1 }),
          comp('Text', {
            content: 'Total: R$ 135,00',
            fontSize: 20,
            fontWeight: '700',
            color: '#EF4444',
            textAlign: 'right',
          }),
          comp('Spacer', { height: 16 }),
          comp('Button', {
            label: 'Confirmar Pedido',
            backgroundColor: '#EF4444',
            textColor: '#FFFFFF',
            borderRadius: 14,
            paddingVertical: 16,
            fontSize: 16,
            fontWeight: '700',
            fullWidth: true,
            actionType: 'alert',
            actionTarget: 'Pedido confirmado! Tempo estimado: 30 min.',
          }),
        ]),
      ],
    },
  },
  {
    id: 'portfolio',
    name: 'Portfólio',
    description: 'Showcase your work and contact info professionally',
    icon: 'work',
    color: '#10B981',
    category: 'Business',
    project: {
      name: 'Portfólio App',
      theme: {
        ...DEFAULT_THEME,
        primaryColor: '#10B981',
        secondaryColor: '#059669',
        backgroundColor: '#F0FDF4',
        surfaceColor: '#FFFFFF',
        textColor: '#064E3B',
        borderRadius: 16,
      },
      screens: [
        screen('About', '#F0FDF4', [
          comp('View', {
            backgroundColor: '#10B981',
            padding: 32,
            borderRadius: 0,
            flexDirection: 'column',
            alignItems: 'center',
            minHeight: 200,
            borderWidth: 0,
          }),
          comp('Spacer', { height: 12 }),
          comp('Text', {
            content: 'John Doe',
            fontSize: 28,
            fontWeight: '800',
            color: '#064E3B',
            textAlign: 'center',
          }),
          comp('Text', {
            content: 'Full-Stack Developer & UI Designer',
            fontSize: 16,
            fontWeight: '500',
            color: '#6EE7B7',
            textAlign: 'center',
          }),
          comp('Spacer', { height: 24 }),
          comp('Card', {
            title: 'About Me',
            subtitle: 'Passionate developer with 5+ years of experience building mobile and web applications.',
            backgroundColor: '#FFFFFF',
            padding: 20,
            borderRadius: 16,
            titleColor: '#064E3B',
            subtitleColor: '#6B7280',
            titleSize: 17,
            subtitleSize: 14,
          }),
          comp('Spacer', { height: 12 }),
          comp('Chart', {
            title: 'Skills',
            labels: ['React', 'Node', 'Design', 'Mobile'],
            values: [90, 75, 80, 85],
            barColor: '#10B981',
            textColor: '#064E3B',
            backgroundColor: '#FFFFFF',
            borderRadius: 16,
          }),
          comp('Spacer', { height: 12 }),
          comp('Button', {
            label: 'View Projects →',
            backgroundColor: '#10B981',
            textColor: '#FFFFFF',
            borderRadius: 14,
            paddingVertical: 14,
            fontSize: 16,
            fontWeight: '700',
            fullWidth: true,
            actionType: 'navigate',
            actionTarget: 'Projects',
          }),
        ]),
        screen('Projects', '#F0FDF4', [
          comp('Header', {
            title: 'My Projects',
            backgroundColor: '#10B981',
            textColor: '#FFFFFF',
            fontSize: 20,
            paddingVertical: 18,
            showBack: true,
          }),
          comp('Spacer', { height: 16 }),
          comp('Card', {
            title: 'AppZap Builder',
            subtitle: 'No-code mobile app builder • React Native, Expo',
            backgroundColor: '#FFFFFF',
            padding: 18,
            borderRadius: 16,
            titleColor: '#064E3B',
            subtitleColor: '#6B7280',
            titleSize: 16,
            subtitleSize: 13,
          }),
          comp('Spacer', { height: 10 }),
          comp('Card', {
            title: 'E-Commerce Platform',
            subtitle: 'Full-stack store with payment integration • Node, React',
            backgroundColor: '#FFFFFF',
            padding: 18,
            borderRadius: 16,
            titleColor: '#064E3B',
            subtitleColor: '#6B7280',
            titleSize: 16,
            subtitleSize: 13,
          }),
          comp('Spacer', { height: 10 }),
          comp('Card', {
            title: 'Fitness Tracker',
            subtitle: 'Health & workout logging app • Flutter, Firebase',
            backgroundColor: '#FFFFFF',
            padding: 18,
            borderRadius: 16,
            titleColor: '#064E3B',
            subtitleColor: '#6B7280',
            titleSize: 16,
            subtitleSize: 13,
          }),
          comp('Spacer', { height: 20 }),
          comp('Button', {
            label: 'Get in Touch',
            backgroundColor: '#10B981',
            textColor: '#FFFFFF',
            borderRadius: 14,
            paddingVertical: 14,
            fontSize: 16,
            fontWeight: '700',
            fullWidth: true,
            actionType: 'alert',
            actionTarget: 'john@example.com — Let\'s build something great!',
          }),
        ]),
      ],
    },
  },
  {
    id: 'store',
    name: 'Loja Simples',
    description: 'App de e-commerce com produtos, carrinho e checkout',
    icon: 'shopping-bag',
    color: '#6366F1',
    category: 'E-commerce',
    project: {
      name: 'Loja App',
      theme: {
        ...DEFAULT_THEME,
        primaryColor: '#6366F1',
        secondaryColor: '#818CF8',
        backgroundColor: '#F5F5FF',
        surfaceColor: '#FFFFFF',
        textColor: '#1E1B4B',
        borderRadius: 14,
      },
      screens: [
        screen('Products', '#F5F5FF', [
          comp('Header', {
            title: 'Nossa Loja',
            backgroundColor: '#6366F1',
            textColor: '#FFFFFF',
            fontSize: 20,
            paddingVertical: 18,
            showBack: false,
          }),
          comp('Spacer', { height: 12 }),
          comp('Text', {
            content: 'Produtos em Destaque',
            fontSize: 18,
            fontWeight: '700',
            color: '#1E1B4B',
            textAlign: 'left',
          }),
          comp('Spacer', { height: 12 }),
          comp('Card', {
            title: 'Tênis Runner Pro',
            subtitle: 'Conforto máximo para corridas • R$ 299,90',
            backgroundColor: '#FFFFFF',
            padding: 18,
            borderRadius: 14,
            titleColor: '#1E1B4B',
            subtitleColor: '#6B7280',
            titleSize: 16,
            subtitleSize: 13,
          }),
          comp('Spacer', { height: 8 }),
          comp('Card', {
            title: 'Mochila Urban',
            subtitle: '30L, compartimento laptop • R$ 189,90',
            backgroundColor: '#FFFFFF',
            padding: 18,
            borderRadius: 14,
            titleColor: '#1E1B4B',
            subtitleColor: '#6B7280',
            titleSize: 16,
            subtitleSize: 13,
          }),
          comp('Spacer', { height: 8 }),
          comp('Card', {
            title: 'Fone Wireless X',
            subtitle: 'ANC, 40h bateria • R$ 449,90',
            backgroundColor: '#FFFFFF',
            padding: 18,
            borderRadius: 14,
            titleColor: '#1E1B4B',
            subtitleColor: '#6B7280',
            titleSize: 16,
            subtitleSize: 13,
          }),
          comp('Spacer', { height: 16 }),
          comp('Button', {
            label: 'Ver Carrinho',
            backgroundColor: '#6366F1',
            textColor: '#FFFFFF',
            borderRadius: 14,
            paddingVertical: 16,
            fontSize: 16,
            fontWeight: '700',
            fullWidth: true,
            actionType: 'navigate',
            actionTarget: 'Checkout',
          }),
        ]),
        screen('Checkout', '#F5F5FF', [
          comp('Header', {
            title: 'Finalizar Compra',
            backgroundColor: '#6366F1',
            textColor: '#FFFFFF',
            fontSize: 20,
            paddingVertical: 18,
            showBack: true,
          }),
          comp('Spacer', { height: 16 }),
          comp('FormField', {
            label: 'Nome Completo',
            placeholder: 'Seu nome',
            labelColor: '#6B7280',
            inputBg: '#FFFFFF',
            borderRadius: 12,
          }),
          comp('Spacer', { height: 12 }),
          comp('FormField', {
            label: 'Endereço de Entrega',
            placeholder: 'Rua, número, complemento',
            labelColor: '#6B7280',
            inputBg: '#FFFFFF',
            borderRadius: 12,
          }),
          comp('Spacer', { height: 12 }),
          comp('FormField', {
            label: 'Número do Cartão',
            placeholder: '•••• •••• •••• ••••',
            labelColor: '#6B7280',
            inputBg: '#FFFFFF',
            borderRadius: 12,
          }),
          comp('Divider', { color: '#C7D2FE', marginVertical: 16, thickness: 1 }),
          comp('Text', {
            content: 'Total: R$ 939,70',
            fontSize: 20,
            fontWeight: '800',
            color: '#6366F1',
            textAlign: 'right',
          }),
          comp('Spacer', { height: 16 }),
          comp('Button', {
            label: 'Confirmar Pagamento',
            backgroundColor: '#6366F1',
            textColor: '#FFFFFF',
            borderRadius: 14,
            paddingVertical: 16,
            fontSize: 16,
            fontWeight: '700',
            fullWidth: true,
            actionType: 'alert',
            actionTarget: 'Compra realizada com sucesso! 🎉',
          }),
        ]),
      ],
    },
  },
];
